apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: reg-cred-argocd-image-updater
  namespace: fast-api
spec:
  encryptedData:
    .dockerconfigjson: AgB0dE6kJHbnWZ8/DXvVgHqpIcqGwSOcJfXjJF1gmZvtyO5Yrcngtf0ZMOdYBeB+rG2wDxW0t/SDZdT+yc9cpAGPHWuOLu/Lk8Q3fBPqehOpIhBhV/HNRyFknDij5aMjLKreJvGlLjLlTPRPOb9Ori1c6A0iDWLfufIqqfzot55Mw3xUBOY/yWxaXSJkKRN0tnwjEfQI53mfNwnHHvpBWJURdwjMpgNYee+te4oYLlvDR6WGWRcIaUWcOMVASs4LYGSFiJnx2ghH+TGJQTYW9PJB0Su7aEtv8lId3HynVIvU6amvVbwmY631r/RXN5aZgjwcA/XrWBi2yLepBJE9/K7j/gMOpXwEZKAAkzBDeFxJoLmw4GsQEzDW6O7oiDIFdkRL0Nlnu8WYs+fMuEnG7Lj0lmm987dV13RhHapBuP2ovXL2l0ox34G1fX4FHevPu/F5rRbB2gXzrf0pJ1RGBde61nv1tVtRoRJP6n1nsUZLcTVPRXb5A1tG14A/bho6zPGViU2yE+EVCcOYBpq5Jo8ZdATJ6BXueloA6ETT7CXpPZaEDrrL4n676xAze+yFvuN2405u3QyGYTo6wOxAQHcvDday97QdELK9YsOExOqObV9cNhuq/FMR0/ve44XUBlMIiY/e0PFBBXOfuPDUyyA1m3g+KkJgdI9+HvgdowZgsIKTueJ+EZ3c5hxhkUsfnscinHcGXSISZWYLvEOpuTqL1+zpZXjmWXoxAsN1qgNJkArAJjkxtBsF3wBRYAm5NmyOQlZszFcNO4jz7ZyhEAJt+UmnNnBHz7JKOHPkF/eoQIoXqelcWjKPJXwdOrMuDhe2ywZIz52eoH6V5+M0RDmDgHN9VXUNB7iwDSokl8LqiG2t+nDatH0A1VuNZyeRuIqZSwI2WgfSGQ/K0G2BgegecGcP2pDrO9eR9WjJeabPJPU1vL20t1Lbt6UI
  template:
    metadata:
      creationTimestamp: null
      name: reg-cred-argocd-image-updater
      namespace: fast-api
    type: kubernetes.io/dockerconfigjson

