apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: reg-cred-argocd-image-updater
  namespace: fast-api
spec:
  encryptedData:
    .dockerconfigjson: AgAwBZIoGNZylcRquTT8sk9Atm0Av8EsmI6qJfZRxg2icREq5yrCGCAfJJ1tR1mp1SNffzwEUWV2BzdHaMIs+rAUQkM0PX1MYUeKDvBQWQvlFa2ihu/e/WqoO9Z0EJkCV/GgCAJ/GZNv/gvz+CrgIZDe+/dGMqZlJfTcesyxUrrF46W+GV//AL8sgP9lENVT49DZT7P/puKZPbxxMwchcIthSm1x9/fwICwNZdrEaPDD2Vp2LTADZ3cLMgfWidmqHgCvJPT7fI+ZND+TOBVwJ+cKVJ7mQEk1SrHByokmglF13uOIN8vR4+UXueACfFiSrlWokS4wjJMoPm6f3gWLPrUBjujYc6OYxCDFEk4ap+Qr2RDWfysq+/E+ZZwWfhyD2XErTh0Gygv35MhY7mgvD8MYy5PwSYUWLmcIaVW5Ydh3r3s/YiDIlZr1AJayXB2HfQNVnVTNCTQ30WIq7hWaiP+9XYob/qXBFO9kOPX/o/nVmK36fhuDsYYbCOgnuPIdgTi2GzTy9G7H1rSnHJo94DgOX3NyYt58oA4RiObWRl5cy/ehmBxQIVFMJ0GQC8Uo7J8mHEU0RWLSVydNZ2QWubRPxtqnKz7v3W58cV8LYxqlS8VKZHEfDa7300a5MKxgNj1ATwjWM2EhNUWJ7qmkV1lJDsErtuteXRurjXzm0vHmYDp8+QRaqJnKS0+KNUhSBmICZJtIhFNBSBtFOOn/t7150diFfDlB7ip3w2PbA1cKd5idHDEzVYymo2EG5L3WGpyobIMsRDD9b8vX9l8df8TxafFOvdDp8jSV7F+ZpHyAyrkLHkwAT+k3XN98hZ60/qdZV2FCDPT1bfm2uajiTFFNY3GxiYz5mk17ah2EMWZ77Qgj7L6zNwpmujbgziPMg0JDefWgn/xAwDvqWkpmeSemIR6/rV/dBeVwZTHK2RGpDln/VXAneqctIvAT
  template:
    metadata:
      creationTimestamp: null
      name: reg-cred-argocd-image-updater
      namespace: fast-api
    type: kubernetes.io/dockerconfigjson

